#### Define bras, kets, brackets
$
\newcommand{\ket}[1]{\left|{#1}\right\rangle}
\newcommand{\bra}[1]{\left\langle{#1}\right|}
\newcommand{\braket}[2]{\left\langle{#1}\middle|{#2}\right\rangle}
$

# Highlights

### Operators

- Hermitian $A^\dagger = A$ has real eigenvalues

- Unitary $U^\dagger U = UU^\dagger = I$ has eigenvalues on the unit circle

- Projection/Projector $P^2 = P$ has eigenvalues 0 and 1

- Positive $\braket{v}{Av} \geq 0 (real)$ for all $\ket{v}$ 

- Normal $N^\dagger N = NN^\dagger$

### Spectral decomposition

Theorem: The eigenvectors $\{e_i\}$ of a normal operator N form a complete orthonormal set and the operator can by decomposed as $N = \lambda_i \ket{e_i}\bra{e_i}$. Since Hermitian, Unitary, and Positive operators are normal, this is true for them as well.

Resolution of the identity: $I = \sum_i \ket{e_i}\bra{e_i}$

### Polar Decomposition

Theorem: Let A be a linear operator on a vector space V. Then there exists a unitary operator U and positive operators J and K such that $A = UJ = KU$, where J and K are given by $J = \sqrt{A^\dagger A}$ and $K = \sqrt{AA^\dagger}$

### Singular Value Decomposition

Theorem: For any square matrix A, there exist unitary matrices U and V, and a diagonal matrix D with non-negative entries such that $ A = UDV$.

### Bell States

$$
\frac{\ket{00} \pm \ket{11}}{\sqrt{2}}
$$

$$
\frac{\ket{01} \pm \ket{10}}{\sqrt{2}}
$$

## Density Matrix

### Composite systems

#### Partial Trace

Let $\ket{a_1},\ket{a_2} \in H_A$, $\ket{b_1}, \ket{b_2} \in H_B$, then 

$$
tr_B\left(\ket{a_1}\bra{a_2}\otimes \ket{b_1}\bra{b_2}\right) \equiv \ket{a_1}\bra{a_2}tr\left(\ket{b_1}\bra{b_2}\right)
= \braket{b_2}{b_1}\left(\ket{a_1}\bra{a_2}\right)
$$

#### Schmidt Decomposition

Theorem: If $\psi$ is a pure state of a composite system AB, then there exist orthonormal states $i^A$ in A and $i^B$ in B, and non-negative real numbers $\lambda_i$, such that 

$$
\ket{\psi} = \sum_i \lambda_i\ket{i^a}\ket{i^B}
$$

#### Purification

Given a possibly mixed state $\rho^A$, we can introduce a system $R$ of the same dimension as A, such that $\rho^A$ is the partial trace of a pure state in the combined system.

In particular, suppose $\rho^A = \sum_i p_i \ket{i^A}\bra{i^A}$ and choose an orthonormal basis $i^R$ in R. Define

$$
\ket{AR} = \sum_i \sqrt{p_i}\ket{i^A}\ket{i^R}
$$

Then $tr_R(\ket{AR}\bra{AR}) = \rho^A$

In [1]:
import numpy as np
from numpy import linalg as la

### Exercise 2.1

Any 3 vectors in 2 dimensions are linearly dependent.

### Exercise 2.2


The representation of A in the $\ket{0},\ket{1}$ basis is 
$\begin{bmatrix}
0 &1\\1 &0 
\end{bmatrix}$


For the basis $e_1 = \ket{0}+\ket{1}, e_2 = \ket{0}-\ket{1}$ (with appropriate normalization), we have

$
Ae_1 = A(\ket{0}+\ket{1}) = \ket{1}+\ket{0} = e_1\\
Ae_2 = A(\ket{0}-\ket{1}) = \ket{1}-\ket{0} = -e_2
$

So in this representation $A = \begin{bmatrix}
1 &0\\0 & -1 
\end{bmatrix}$


### Exercise 2.6

$(au, v) = (v,au)^* = (a(v,u))^* = a^*(v,u)^* = a^*(u,v)$  

### Exercise 2.8 

The Gram-Schmidt process can be established by induction. See for example, https://en.wikipedia.org/wiki/Gram–Schmidt_process


### Exercise 2.9 

$$
\sigma_i = \bra{0}\sigma_i\ket{0}\ket{0}\bra{0} +
 \bra{0}\sigma_i\ket{1}\ket{0}\bra{1} + 
 \bra{1}\sigma_i\ket{0}\ket{1}\bra{0} +
  \bra{1}\sigma_i\ket{1}\ket{1}\bra{1}
$$

$$
\sigma_0 = \ket{0}\bra{0} + \ket{1}\bra{1}
$$

$$
\sigma_1 = \sigma_X = X = \ket{0}\bra{1} + \ket{1}\bra{0}
$$

$$
\sigma_2 = \sigma_Y = Y = i \left(\ket{1}\bra{0} - \ket{0}\bra{1}\right)
$$

$$
\sigma_3 = \sigma_Z = Z = \ket{0}\bra{0} - \ket{1}\bra{1}
$$

### Exercise 2.10

The matrix is 1 in position (j,k) and 0 elsewhere.

### Exercise 2.11

Find the eigenvectors, eigenvalues, and diagonal representations of the Pauli Matrices.

I solve this computationally with numpy.

In [6]:
X = np.matrix([[0, 1], [1, 0]])
Y = np.matrix([[0, -1j], [1j, 0]])
Z = np.matrix([[1, 0], [0, -1]])


In [7]:
la.eig(X)

(array([ 1., -1.]),
 matrix([[ 0.70710678, -0.70710678],
         [ 0.70710678,  0.70710678]]))

In [8]:
l, U = la.eig(X)

np.round(U.H*X*U)

matrix([[ 1.,  0.],
        [ 0., -1.]])

In [9]:
la.eig(Y)

(array([ 1.+0.j, -1.+0.j]),
 matrix([[-0.        -0.70710678j,  0.70710678+0.j        ],
         [ 0.70710678+0.j        ,  0.        -0.70710678j]]))

In [10]:
l, U = la.eig(Y)

np.round(U.H*Y*U)

matrix([[ 1.+0.j,  0.+0.j],
        [ 0.-0.j, -1.+0.j]])

In [11]:
la.eig(Z)

(array([ 1., -1.]),
 matrix([[1., 0.],
         [0., 1.]]))

### Problem 2.12

The matrix has only one eigenvector $(0, 1)^T$ therefore it cannot be diagonalized.

### Exercise 2.16

$$
P^2 = \sum_i \ket{i}\bra{i} \sum_j \ket{j}\bra{j} =\\
\sum_i\sum_j \ket{i}\braket{i}{j}\bra{j} = \\
\sum_i\sum_j \delta_{ij}\ket{i}\bra{j} = \\
\sum_i \ket{i}\bra{i} = P
$$

### Exercise 2.17

The easiest way to show it is via spectral decomposition.
Suppose the normal operator $A$ has real eigenvalues and spectral decomposition

$A = \sum a_i \ket{i}\bra{i}$

Then

$$
A^\dagger = \sum a^*_i (\ket{i}\bra{i})^\dagger = \sum a_i \ket{i}\bra{i} = A
$$

### Exercise 2.18

$U\ket{x} = \lambda\ket{x} \implies \bra{x}U^\dagger = \lambda^*\bra{x}$

combining the two

$\bra{x}U^\dagger U\ket{x} = |\lambda|^2\braket{x}{x} \implies \braket{x}{x} =  |\lambda|^2\braket{x}{x} $

from which we conclude $|\lambda|^2 = 1$

### Exercise 2.22

Using inner product notation
$$
(v_1, Hv_2) = (Hv_1,v_2) \implies\\
\lambda_2(v_1,v_2) = \lambda_1(v_1,v_2)
$$

Since the lambdas ae distinct, we must have $(v_1,v_2) = 0$

### Exercise 2.23

$P\ket{x} = \lambda x \implies P^2 \ket{x} = \lambda^2 \ket{x}$ but also $P^2 \ket{x} =  \lambda \ket{x}$, so it has to be $\lambda = \lambda^2$ which means it is either 0 or 1.

### Exercise 2.24

Let $B = \frac{A+A^\dagger}{2}$, $C = -i\frac{A-A^\dagger}{2}$. Then $A = B+iC$.

Since $A$ is positive, $\bra{x}A\ket{x}$ is real for every $x$, so $\bra{x}B\ket{x}+i\bra{x}C\ket{x}$ is real. But since $B,C$ are Hermitian, $\bra{x}B\ket{x}$ and $\bra{x}C\ket{x}$ are real. This means that $C = 0$.

### Exercise 2.25

$$
\bra{v}A^\dagger A\ket{v} = \braket{Av}{Av} = ||Av||^2 \geq 0
$$

### Exercise 2.27

In [12]:
np.kron(X,Z)

matrix([[ 0,  0,  1,  0],
        [ 0,  0,  0, -1],
        [ 1,  0,  0,  0],
        [ 0, -1,  0,  0]])

In [13]:
I = np.eye(2)
np.kron(I,X)

matrix([[0., 1., 0., 0.],
        [1., 0., 0., 0.],
        [0., 0., 0., 1.],
        [0., 0., 1., 0.]])

In [14]:
np.kron(X,I)

matrix([[0., 0., 1., 0.],
        [0., 0., 0., 1.],
        [1., 0., 0., 0.],
        [0., 1., 0., 0.]])

### Exercise 2.29

$$
(U\otimes U')^\dagger (U\otimes U') (\ket{x}\otimes\ket{y}) = \\
(U^\dagger \otimes U'^\dagger)(\ket{Ux}\otimes\ket{U'y}) = \\
(\ket{U^\dagger Ux}\otimes\ket{ U'^\dagger U'y}) = \\
\ket{x}\otimes\ket{y}
$$

### Execise 2.30

This follows directly from the last part of exercise 2.28

### Exercise 2.33

TODO

### Exercise 2.34

The matrix has eignevalue 7 with eigenvector $[1,1]/\sqrt(2)$ and 1 with eigenvector  $[1,-1]/\sqrt(2)$.

We have 
$$
[1,1]/\sqrt(2)\otimes [1,1]/\sqrt(2) = \frac{1}{2}
\begin{bmatrix} 1 &1\\ 1 & 1\end{bmatrix}
$$

and 

$$
[1,-1]/\sqrt(2)\otimes [1,-1]/\sqrt(2) = \frac{1}{2}
\begin{bmatrix} 1 & -1\\ -1 & 1\end{bmatrix}
$$

so

$$
f(A) = \frac{1}{2}\begin{bmatrix} 
f(7)+f(1) & f(7)-f(1)\\ 
 f(7)-f(1) & f(7)+f(1)
\end{bmatrix}
$$


### Exercise 2.36

By inspection

### Exercise 2.37

$$
tr(AB) = tr(A_i^j B_j^k) = A_i^j B_j^i
$$

$$
tr(BA) = tr(B_i^j A_j^k) = B_i^j A_j^i
$$

so $tr(AB) = tr(BA)$

### Exercise 2.39

Inner product of operators $(A,B) := tr(A^\dagger B)$

1) We must show the properties of the inner product in section 2.1.4

i) $(A,cB)= tr(A^\dagger cB) = c tr(A^\dagger B) = c(A,B)$

ii) $(A,B)^* = tr(A^\dagger B)^* = tr(B^\dagger A) = (B, A)$

ii) $(A,A) = tr(A^\dagger A) = \sum_i |a_i|^2 \geq 0$ with equality if all the eigenvalues are 0.

### Exercise 2.41

show $\{\sigma_i, \sigma_j \} = I\delta_{ij}$

### Exercise 2.42

Show $$AB = \frac{[A,B] + \{A,B\}}{2}$$

$$
[A,B] + \{A,B\} = AB-BA+AB+BA = 2AB
$$

### Exercise 2.47

$$
(-i[A,B])^\dagger = i(AB-BA)^\dagger = i(B^\dagger A^\dagger - A^\dagger B^\dagger) = i(BA-AB) = -i(AB-BA) = -i[A,B]
$$

### Exercise 2.48

The polar decomposition of $A$ is $A = UJ = KU$, where $U$ is unitary and $j,K$ positive.

- If $A$ is positive, then $J= K = A$ and $U = I$ 
- If $A$ is unitary, $U = A$ and $J = K = I$
- If $A$ is Hermitian, then $J = K = H$ and $U = I$, because every Hermitian matrix is positive.



### Exercise 2.49

If $N$ is normal is has a representation $N = \sum_i \lambda_i \ket{i}\bra{i}$.

$$
N^\dagger N = \sum_i \lambda_i \ket{i}\bra{i} \sum_j \lambda_j^* \ket{j}\bra{j} =
\sum_{ij} \lambda_i \lambda_j^* \ket{i}\braket{i}{j}\bra{j} = \sum_i | \lambda_i|^2 \ket{i}\bra{i}
$$

so $J = \sqrt(N^\dagger N) =  \sum_i | \lambda_i| \ket{i}\bra{i}$

Let $U := \sum_i e^{i\theta_i}  \ket{i}\bra{i}$, where $\theta_i = arg(\lambda_i)$\

Then $N = UJ$


### Exercise 2.50

$
A^\dagger = \begin{bmatrix}1 & 1\\0 & 1\end{bmatrix}$

$$
A^\dagger A = \begin{bmatrix}1 & 1\\0 & 1\end{bmatrix}\begin{bmatrix}1 & 0\\1 & 1\end{bmatrix} 
= \begin{bmatrix} 2 & 1\\1 & 1\end{bmatrix} 
$$

$$
AA^\dagger = \begin{bmatrix}1 & 0\\1 & 1\end{bmatrix}\begin{bmatrix}1 & 1\\0 & 1\end{bmatrix}
= \begin{bmatrix}1 & 1\\1 & 2\end{bmatrix} 
$$


In [40]:
evalues, evectors = np.linalg.eig(np.matrix([[2, 1], [1,1]]))
J = evectors @ np.diag(np.sqrt(evalues)) @ np.linalg.inv(evectors)
J

matrix([[1.34164079, 0.4472136 ],
        [0.4472136 , 0.89442719]])

In [41]:
evalues, evectors = np.linalg.eig(np.matrix([[1, 1], [1,2]]))
K = evectors @ np.diag(np.sqrt(evalues)) @ np.linalg.inv(evectors)
K

matrix([[0.89442719, 0.4472136 ],
        [0.4472136 , 1.34164079]])

TODO: Find U

### Exercises 2.51-2.53

In [8]:

H = np.matrix([[1, 1], [1, -1]]) / np.sqrt(2)
H.transpose()

matrix([[ 0.70710678,  0.70710678],
        [ 0.70710678, -0.70710678]])

In [9]:
np.round(H**2)

matrix([[ 1., -0.],
        [-0.,  1.]])

In [10]:
la.eig(H)

(array([ 1., -1.]),
 matrix([[ 0.92387953, -0.38268343],
         [ 0.38268343,  0.92387953]]))

### Exercise 2.54

Since A and B commute, there is a unitary matrix U such that 
$U^\dagger A U = diag(a_1, \ldots, a_n)$ and $U^\dagger B U = diag(b_1, \ldots, b_n)$.

Therefore

$$
exp(A)exp(B) = U^\dagger diag(e^a_i) diag(e^b_i) U = U^\dagger diag(e^{a_i + b_i}) U = exp(A+B)$ 
$$

### Exercise 2.57

Just apply 2.92 and 2.93 twice.

### Exercise 2.58

The expectation is the eigenvalue corresponding to $\psi$ and the variance is 0.

### Exercise 2.59

$E[X] = \bra{0}X\ket{0} = \braket{0}{1} = 0$

$std(X) = \left(\bra{0}X^2\ket{0} - E[X]^2\right)^\frac{1}{2} = 1$ 

### Exercise 2.60

Let $\Sigma := \sum_{i=1}^3 v_i \sigma_i := v\cdot\sigma$

1) To show the eigenvalues are $\pm 1$ it suffices to show $\Sigma^2 = I$

$$
\Sigma^2 = \sum_{ij}v_i v_j \sigma_i \sigma_j = \sum_i v_i^2 \sigma_i^2 + \sum_{i\neq j}v_i v_j \sigma_i \sigma_j = 
\sum_i v_i^2 + \sum_{i\neq j} \epsilon_{ij}^k\sigma_k
$$

The first terms sums to the identity since v is a unit vector and the second term cancels out, so $\Sigma^2 = I$.


2) To show that P is a projector we must show $P^2 = P$.

$$
P^2 = \frac{1}{4}(I+\sum_i v_i \sigma_i)(I+\sum_j v_j \sigma_j) = 
 \frac{1}{4}\left(I + 2\sum_i v_i \sigma_i + \sum_{i} v_i^2 +  \sum_{i\neq j} \epsilon_{ij}^k\sigma_k \right) =\\
 \frac{1}{4}\left(2I + 2 v\cdot\sigma \right) = \frac{I + v\cdot\sigma}{2} = P
$$

The calculation for the minus sign version is the same.


3) To show thet P projects on the eigenspace spanned by the eigenvectors, it suffices to show that every eigenvector is projected onto the same subspace.

let $\ket{x}$ be an eigenvector of $\Sigma$ with eigenvalue 1

$$
(I+\Sigma)\ket{x} = 2\ket{x}
$$

so it is in the same subspace. The same result follows for the the other projector and an eigenvector of -1

### Exercise 2.61

VERIFY

Probability = ${1+v_3}{2}$

State = $(1+v_3)\ket{0} + (v_1+iv_2)\ket{1}$

### Exercise 2.62

If $M_m = E_m$, then $M_m = M_m^\dagger M_m$.

Taking the transpose of both sides

$M_m^\dagger = M_m^\dagger M_m = M_m$

from which we conclude $M_m^2 = M_m$, therefore it is a projection.

### Exercise 2.65

Apply H to these states to get $\ket{1}$ and $\ket{0}$

### Exercise 2.66

$X_1 Z_2\ket{00} = \ket{10}$
$X_1 Z_2\ket{11} = -\ket{01}$

so $X_1 Z_2\ket{\psi} = \frac{\ket{10}-\ket{01}}{\sqrt{2}}$

and since Bell states are orthonormal the inner product of this with $\psi$ is 0.

### Exercise 2.67

The idea is to extend the $m \times m$ matrix $U$ to an $n \times n$ matrix 
$\begin{bmatrix}U & 0\\ 0 & I\end{bmatrix}$

First, start by choosing an orthonormal basis $e_1, \ldots, e_n$ such that $e_1, \ldots, e_m$ are in $W$ and the remaining are in $W^\perp$.

Then note that the images $\epsilon_j = Ue_j$ are also orthonormal by the inner product preserving property of $U$:
$\braket{\epsilon_i}{\epsilon_j} = \braket{Ue_i}{Ue_j} \braket{e_i}{e_j} = \delta_{ij}$ 

Using the Gram-Schmidt process extend $\epsilon_1, \ldots \epsilon_m$ to a full orthonormal basis that spans $Im(U)^\perp$.

The for a vector $v = \sum_i v^i e_i$, define $U'v \equiv \sum_i v^i \epsilon_i$.

### Exercise 2.68

Let $\ket{a} = a_1\ket{0}+a_2\ket{1}$, $\ket{b} = b_1\ket{0}+b_2\ket{1}$

Then

$$
\ket{a}\otimes \ket{b} = ( a_1\ket{0}+a_2\ket{1})\otimes (b_1\ket{0}+b_2\ket{1}) =
a_1 b_1\ket{00}+a_2 b_1\ket{10}+a_1 b_2\ket{01}+a_2 b_2 \ket{11}
$$

So we must have $a_1 b_1 = a_2 b_2 = 1$ and  $a_1 b_2 = a_2 b_1 = 0$, which is impossible.

### Exercise 2.71

Note that $tr(\ket{v}\bra{w}) = \braket{w}{v}$.

Also, by the Schwartz inequality

$
|\braket{v}{w}|^2 \leq |v|^2|w|^2
$

so for normalized vectors

$
|\braket{v}{w}|^2 \leq 1
$

$$
\rho^2 = \sum_i p_i \ket{x_i}\bra{x_i}\sum_j p_j \ket{x_j}\bra{x_j} =
\sum_{ij} p_i p_j \braket{x_i}{x_j}\ket{x_i}\bra{x_j}
$$

$$
tr(\rho^2) = \sum_{ij} p_i p_j \braket{x_i}{x_j} tr(\ket{x_i}\bra{x_j}) =  
\sum_{ij} p_i p_j \braket{x_i}{x_j} \braket{x_j}{x_i}=\\
\sum_{ij} p_i p_j |\braket{x_i}{x_j}|^2 \leq \sum_{ij} p_i p_j = \sum_i p_i \sum_j p_j = 1
$$

### Exercise 2.72

1) We must show that the trace is 1 and the operator is positive

$tr(\rho) = \frac{tr(I)+ \sum_i r_i tr(\sigma_i)}{2} = \frac{2+0}{2} = 1$

To show it is positive, we must show $<v,\rho v> \geq 0$ for all v

$$
<v, \rho v> = \frac{1}{2}\left(|v|^2 + \sum_i r_i <v_i ,\sigma_i v_i>\right)
$$

Since the $\sigma_i$ are Hermitian, $<v_i ,\sigma_i v_i>$ is real. We can use the fact that $|r| \leq 1$ to show that the expression is positive.

2. $ r = 0$

3)

$$
\rho^2 = \left(\frac{I+r^i \sigma_i}{2}\right)\left(\frac{I+r^j \sigma_j}{2}\right)=\\
\frac{1}{4}\left(I + 2r^i \sigma_i + r^i r^j \sigma_i \sigma_j \right) = \\
\frac{1}{4}\left(I + 2r^i \sigma_i + \sum_i (r^i)^2 \sum_{j \neq i} r^i r^j e_{ij}^k \sigma_k \right)
$$

Using the fact that $tr(\sigma_i) = 0$, we have

$$
tr(\rho^2) = \frac{1}{4}(2 + 2|r|^2) = \frac{1}{2}(1+|r|^2)
$$

which is 1 iff $|r| = 1$

4)  TODO

### Exercise 2.73 

TODO

### Exercise 2.74

$$
\rho^A = tr_B(\rho^{AB}) = tr_B(\ket{a}\ket{b}\bra{b}\bra{a}) = |b|^2\ket{a}\bra{a}
$$

### Exercise 2.75

Pick $\ket{\psi} = \frac{\ket{00} \pm \ket{11}}{\sqrt{2}}$. Then

$$
\ket{\psi}\bra{\psi} = \frac{1}{2}\left[ \ket{00}\bra{00} + \ket{11}\bra{11} + \ket{01}\bra{01} + \ket{10}\bra{10}\right]  
$$

$$
tr_B(\ket{\psi}\bra{\psi}) = \frac{1}{2}\left[\ket{0}\bra{0} + \ket{1}\bra{1} \right]  
$$

where I have used the orthonormality of 0 and 1 to get rid of the cross-terms. The calculation for the other states is similar.

### Exercise 2.76

The generalization follows from the fact that SVD is possible for non-square matrices.

### Exercise 2.78

1) Prove that $\psi$ is a product state iff it has Schmidt number 1.

If  $\ket{\psi} = \ket{a}\ket{b}$  then it has a Schmidt representation $ |a||b|\ket{a/|a|}\ket{b/|b|}$ which has rank 1. Conversely, if $\ket{\psi}$ has a rank 1  Schmidt representation $\lambda\ket{a}\ket{b}$ then it is clearly a product state.

2) Prove that $\psi$ is a product state iff  $\rho^A$ (and $\rho^B)$ are pure states

If $\ket{\psi} = \ket{a}\ket{b}$, then $\rho = \ket{a}\ket{b}\otimes\bra{a}\bra{b}$, so 
$\rho^A = |b|^2\ket{a}\bra{a}$ which is a pure state (same for $\rho^B$).

If $\rho^A = \ket{a}\bra{a}$ and $\rho^B = \ket{b}\bra{b}$, then 
$\rho = \rho^A \otimes \rho^B = \ket{a}\ket{b}\otimes\bra{a}\bra{b}$, which is a product state.
